export async function fetchRecipes() {
  await wait(300)
  return [
    { id: 1, title: 'Паста Карбонара', time: 20, servings: 2, calories: 450, image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400', isFavorite: false },
    { id: 2, title: 'Греческий салат', time: 10, servings: 4, calories: 180, image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400', isFavorite: true },
    { id: 3, title: 'Борщ украинский', time: 90, servings: 6, calories: 320, image: 'https://images.unsplash.com/photo-1604908815674-0f8a4d5e1f5e?w=400', isFavorite: false },
    { id: 4, title: 'Панкейки с ягодами', time: 15, servings: 2, calories: 250, image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400', isFavorite: false },
    { id: 5, title: 'Том Ям', time: 30, servings: 3, calories: 280, image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400', isFavorite: true },
    { id: 6, title: 'Цезарь с курицей', time: 20, servings: 2, calories: 380, image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400', isFavorite: false },
    { id: 7, title: 'Лазанья', time: 60, servings: 4, calories: 520, image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400', isFavorite: false },
    { id: 8, title: 'Суши роллы', time: 40, servings: 2, calories: 310, image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400', isFavorite: true },
    { id: 9, title: 'Тирамису', time: 25, servings: 6, calories: 420, image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400', isFavorite: false },
    { id: 11, title: 'Паста Карбонара', time: 20, servings: 2, calories: 450, image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400', isFavorite: false },
    { id: 12, title: 'Греческий салат', time: 10, servings: 4, calories: 180, image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400', isFavorite: true },
    { id: 13, title: 'Борщ украинский', time: 90, servings: 6, calories: 320, image: 'https://images.unsplash.com/photo-1604908815674-0f8a4d5e1f5e?w=400', isFavorite: false },
    { id: 14, title: 'Панкейки с ягодами', time: 15, servings: 2, calories: 250, image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400', isFavorite: false },
    { id: 15, title: 'Том Ям', time: 30, servings: 3, calories: 280, image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400', isFavorite: true },
    { id: 16, title: 'Цезарь с курицей', time: 20, servings: 2, calories: 380, image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400', isFavorite: false },
    { id: 17, title: 'Лазанья', time: 60, servings: 4, calories: 520, image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400', isFavorite: false },
    { id: 18, title: 'Суши роллы', time: 40, servings: 2, calories: 310, image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400', isFavorite: true },
    { id: 19, title: 'Тирамису', time: 25, servings: 6, calories: 420, image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400', isFavorite: false },
    { id: 211, title: 'Паста Карбонара', time: 20, servings: 2, calories: 450, image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400', isFavorite: false },
    { id: 212, title: 'Греческий салат', time: 10, servings: 4, calories: 180, image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400', isFavorite: true },
    { id: 213, title: 'Борщ украинский', time: 90, servings: 6, calories: 320, image: 'https://images.unsplash.com/photo-1604908815674-0f8a4d5e1f5e?w=400', isFavorite: false },
    { id: 214, title: 'Панкейки с ягодами', time: 15, servings: 2, calories: 250, image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400', isFavorite: false },
    { id: 215, title: 'Том Ям', time: 30, servings: 3, calories: 280, image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400', isFavorite: true },
    { id: 216, title: 'Цезарь с курицей', time: 20, servings: 2, calories: 380, image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400', isFavorite: false },
    { id: 217, title: 'Лазанья', time: 60, servings: 4, calories: 520, image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400', isFavorite: false },
    { id: 218, title: 'Суши роллы', time: 40, servings: 2, calories: 310, image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400', isFavorite: true },
    { id: 219, title: 'Тирамису', time: 25, servings: 6, calories: 420, image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400', isFavorite: false },
    { id: 2211, title: 'Паста Карбонара', time: 20, servings: 2, calories: 450, image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400', isFavorite: false },
    { id: 2212, title: 'Греческий салат', time: 10, servings: 4, calories: 180, image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400', isFavorite: true },
    { id: 2213, title: 'Борщ украинский', time: 90, servings: 6, calories: 320, image: 'https://images.unsplash.com/photo-1604908815674-0f8a4d5e1f5e?w=400', isFavorite: false },
    { id: 2214, title: 'Панкейки с ягодами', time: 15, servings: 2, calories: 250, image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400', isFavorite: false },
    { id: 2215, title: 'Том Ям', time: 30, servings: 3, calories: 280, image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400', isFavorite: true },
    { id: 2216, title: 'Цезарь с курицей', time: 20, servings: 2, calories: 380, image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400', isFavorite: false },
    { id: 2217, title: 'Лазанья', time: 60, servings: 4, calories: 520, image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400', isFavorite: false },
    { id: 2218, title: 'Суши роллы', time: 40, servings: 2, calories: 310, image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400', isFavorite: true },
    { id: 2219, title: 'Тирамису', time: 25, servings: 6, calories: 420, image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400', isFavorite: false },
  ]
}

export async function fetchRecipeById(id) {
  await wait(400)
  const recipes = {
    1: {
      id: 1,
      title: 'Паста Карбонара',
      time: 20,
      servings: 2,
      calories: 450,
      image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800',
      description: 'Классическая итальянская паста с беконом, яйцом и пармезаном. Простое, но невероятно вкусное блюдо.',
      ingredients: [
        { name: 'Спагетти', amount: '200 г' },
        { name: 'Бекон', amount: '100 г' },
        { name: 'Яйца', amount: '2 шт' },
        { name: 'Пармезан', amount: '50 г' },
        { name: 'Черный перец', amount: 'по вкусу' },
        { name: 'Соль', amount: 'по вкусу' },
      ],
      steps: [
        'Отварите спагетти в подсоленной воде до состояния аль денте.',
        'Обжарьте нарезанный бекон на сковороде до хрустящей корочки.',
        'Взбейте яйца с тертым пармезаном и черным перцем.',
        'Слейте воду с пасты, оставив немного жидкости.',
        'Смешайте горячую пасту с беконом, затем добавьте яичную смесь.',
        'Быстро перемешайте, чтобы яйца не свернулись. Подавайте немедленно.',
      ],
      tags: ['Итальянская кухня', 'Быстро', 'Ужин'],
      isFavorite: false,
    },
    2: {
      id: 2,
      title: 'Греческий салат',
      time: 10,
      servings: 4,
      calories: 180,
      image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
      description: 'Свежий средиземноморский салат с огурцами, помидорами, фетой и оливками.',
      ingredients: [
        { name: 'Огурцы', amount: '2 шт' },
        { name: 'Помидоры', amount: '3 шт' },
        { name: 'Фета', amount: '150 г' },
        { name: 'Оливки', amount: '100 г' },
        { name: 'Красный лук', amount: '1 шт' },
        { name: 'Оливковое масло', amount: '3 ст.л.' },
        { name: 'Лимонный сок', amount: '1 ст.л.' },
      ],
      steps: [
        'Нарежьте огурцы и помидоры крупными кубиками.',
        'Нарежьте красный лук тонкими полукольцами.',
        'Нарежьте фету кубиками.',
        'Смешайте овощи, добавьте оливки.',
        'Заправьте оливковым маслом и лимонным соком.',
        'Аккуратно перемешайте и подавайте.',
      ],
      tags: ['Салат', 'Средиземноморская кухня', 'Вегетарианское'],
      isFavorite: true,
    },
    3: {
      id: 3,
      title: 'Борщ украинский',
      time: 90,
      servings: 6,
      calories: 320,
      image: 'https://images.unsplash.com/photo-1604908815674-0f8a4d5e1f5e?w=800',
      description: 'Традиционный украинский суп на мясном бульоне со свеклой и капустой.',
      ingredients: [
        { name: 'Говядина на кости', amount: '500 г' },
        { name: 'Свекла', amount: '2 шт' },
        { name: 'Капуста', amount: '300 г' },
        { name: 'Картофель', amount: '3 шт' },
        { name: 'Морковь', amount: '1 шт' },
        { name: 'Лук', amount: '1 шт' },
        { name: 'Томатная паста', amount: '2 ст.л.' },
        { name: 'Чеснок', amount: '3 зубчика' },
        { name: 'Уксус', amount: '1 ст.л.' },
        { name: 'Сметана', amount: 'для подачи' },
      ],
      steps: [
        'Отварите мясо до готовности (около 1,5 часов), снимая пену.',
        'Нарежьте овощи: свеклу и морковь соломкой, капусту — тонко.',
        'Обжарьте лук и морковь, добавьте томатную пасту.',
        'Отдельно потушите свеклу с уксусом.',
        'В бульон добавьте картофель, затем капусту.',
        'За 15 минут до готовности добавьте зажарку и свеклу.',
        'Подавайте со сметаной и чесноком.',
      ],
      tags: ['Украинская кухня', 'Суп', 'Обед'],
      isFavorite: false,
    },
    4: {
      id: 4,
      title: 'Панкейки с ягодами',
      time: 15,
      servings: 2,
      calories: 250,
      image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
      description: 'Пышные американские блинчики с ягодами и кленовым сиропом.',
      ingredients: [
        { name: 'Мука', amount: '150 г' },
        { name: 'Молоко', amount: '200 мл' },
        { name: 'Яйцо', amount: '1 шт' },
        { name: 'Сахар', amount: '2 ст.л.' },
        { name: 'Разрыхлитель', amount: '1 ч.л.' },
        { name: 'Соль', amount: 'щепотка' },
        { name: 'Ягоды', amount: '100 г' },
        { name: 'Кленовый сироп', amount: 'для подачи' },
      ],
      steps: [
        'Смешайте сухие ингредиенты: муку, сахар, разрыхлитель, соль.',
        'Взбейте яйцо с молоком.',
        'Соедините жидкие и сухие компоненты, не перемешивая слишком долго.',
        'Разогрейте сковороду, влейте порцию теста.',
        'Жарьте до появления пузырьков, переверните.',
        'Подавайте с ягодами и кленовым сиропом.',
      ],
      tags: ['Завтрак', 'Десерт', 'Быстро'],
      isFavorite: false,
    },
    5: {
      id: 5,
      title: 'Том Ям',
      time: 30,
      servings: 3,
      calories: 280,
      image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800',
      description: 'Острый тайский суп с креветками, лемонграссом и галангалом.',
      ingredients: [
        { name: 'Креветки', amount: '300 г' },
        { name: 'Лемонграсс', amount: '2 стебля' },
        { name: 'Галангал', amount: '3 кусочка' },
        { name: 'Листья лайма', amount: '5 шт' },
        { name: 'Грибы', amount: '150 г' },
        { name: 'Помидоры черри', amount: '100 г' },
        { name: 'Паста чили', amount: '2 ст.л.' },
        { name: 'Рыбный соус', amount: '2 ст.л.' },
        { name: 'Сок лайма', amount: '2 ст.л.' },
      ],
      steps: [
        'Вскипятите воду, добавьте лемонграсс, галангал и листья лайма.',
        'Варите 5 минут для аромата.',
        'Добавьте пасту чили и грибы.',
        'Положите креветки и помидоры черри.',
        'Варите до готовности креветок (3–4 минуты).',
        'Заправьте рыбным соусом и соком лайма перед подачей.',
      ],
      tags: ['Тайская кухня', 'Суп', 'Острое'],
      isFavorite: true,
    },
    6: {
      id: 6,
      title: 'Цезарь с курицей',
      time: 20,
      servings: 2,
      calories: 380,
      image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
      description: 'Популярный салат с курицей гриль, пармезаном и соусом Цезарь.',
      ingredients: [
        { name: 'Куриная грудка', amount: '200 г' },
        { name: 'Салат романо', amount: '1 кочан' },
        { name: 'Пармезан', amount: '50 г' },
        { name: 'Гренки', amount: '50 г' },
        { name: 'Майонез', amount: '3 ст.л.' },
        { name: 'Чеснок', amount: '1 зубчик' },
        { name: 'Лимонный сок', amount: '1 ч.л.' },
        { name: 'Анчоусы', amount: '2 шт (опционально)' },
      ],
      steps: [
        'Обжарьте или запеките куриную грудку, нарежьте ломтиками.',
        'Приготовьте соус: смешайте майонез, чеснок, лимонный сок, анчоусы.',
        'Порвите салат руками.',
        'Смешайте салат с соусом.',
        'Добавьте курицу, гренки и стружку пармезана.',
        'Подавайте немедленно.',
      ],
      tags: ['Салат', 'Обед', 'С курицей'],
      isFavorite: false,
    },
    7: {
      id: 7,
      title: 'Лазанья',
      time: 60,
      servings: 4,
      calories: 520,
      image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800',
      description: 'Итальянская запеканка с мясным соусом болоньезе и сыром.',
      ingredients: [
        { name: 'Листы лазаньи', amount: '9 шт' },
        { name: 'Фарш говяжий', amount: '500 г' },
        { name: 'Помидоры в собственном соку', amount: '400 г' },
        { name: 'Лук', amount: '1 шт' },
        { name: 'Морковь', amount: '1 шт' },
        { name: 'Молоко', amount: '500 мл' },
        { name: 'Мука', amount: '3 ст.л.' },
        { name: 'Сливочное масло', amount: '50 г' },
        { name: 'Моцарелла', amount: '200 г' },
        { name: 'Пармезан', amount: '50 г' },
      ],
      steps: [
        'Приготовьте болоньезе: обжарьте лук, морковь, добавьте фарш, затем помидоры. Тушите 20 минут.',
        'Приготовьте соус бешамель: растопите масло, добавьте муку, влейте молоко, варите до густоты.',
        'Смажьте форму маслом, выложите слой лазаньи.',
        'Чередуйте слои: соус болоньезе, бешамель, листы лазаньи.',
        'Верхний слой — бешамель и тертый сыр.',
        'Запекайте при 180°C 30–35 минут до золотистой корочки.',
      ],
      tags: ['Итальянская кухня', 'Ужин', 'Запеканка'],
      isFavorite: false,
    },
    8: {
      id: 8,
      title: 'Суши роллы',
      time: 40,
      servings: 2,
      calories: 310,
      image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
      description: 'Домашние роллы с лососем, огурцом и авокадо.',
      ingredients: [
        { name: 'Рис для суши', amount: '200 г' },
        { name: 'Нори', amount: '4 листа' },
        { name: 'Лосось', amount: '150 г' },
        { name: 'Огурец', amount: '1 шт' },
        { name: 'Авокадо', amount: '1 шт' },
        { name: 'Рисовый уксус', amount: '2 ст.л.' },
        { name: 'Сахар', amount: '1 ч.л.' },
        { name: 'Соль', amount: '1/2 ч.л.' },
        { name: 'Васаби, имбирь, соевый соус', amount: 'для подачи' },
      ],
      steps: [
        'Отварите рис, заправьте смесью уксуса, сахара и соли.',
        'Нарежьте рыбу, огурец и авокадо длинными брусочками.',
        'Положите нори на бамбуковую циновку, распределите рис.',
        'Выложите начинку посередине.',
        'Сверните ролл с помощью циновки.',
        'Нарежьте острым ножом на 6–8 кусочков.',
      ],
      tags: ['Японская кухня', 'Суши', 'Морепродукты'],
      isFavorite: true,
    },
    9: {
      id: 9,
      title: 'Тирамису',
      time: 25,
      servings: 6,
      calories: 420,
      image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800',
      description: 'Знаменитый итальянский десерт с маскарпоне и кофе.',
      ingredients: [
        { name: 'Печенье савоярди', amount: '200 г' },
        { name: 'Маскарпоне', amount: '500 г' },
        { name: 'Яйца', amount: '4 шт' },
        { name: 'Сахар', amount: '100 г' },
        { name: 'Крепкий кофе', amount: '200 мл' },
        { name: 'Какао-порошок', amount: 'для украшения' },
        { name: 'Ликер Амаретто', amount: '2 ст.л. (опционально)' },
      ],
      steps: [
        'Сварите крепкий кофе, остудите, при желании добавьте ликер.',
        'Отделите желтки от белков. Взбейте желтки с сахаром до светлой массы.',
        'Добавьте маскарпоне, перемешайте.',
        'Взбейте белки в крепкую пену, аккуратно введите в сырную массу.',
        'Быстро обмакните печенье в кофе, выложите слой в форму.',
        'Покройте кремом, повторите слои.',
        'Посыпьте какао, уберите в холодильник на 4 часа.',
      ],
      tags: ['Десерт', 'Итальянская кухня', 'Без выпечки'],
      isFavorite: false,
    },
  }
  return recipes[id] || null
}

function wait(ms) { return new Promise(r => setTimeout(r, ms)) }
  